### ISSUE TITLE
Data in 'inference.py'

### ISSUE THREAD

**Issue by WonsokYoo** [jhultman/PV-RCNN#12]
Actually I tried to download '000007.bin' and '000008.bin' by myself but by any chance.. do you have any script to download the KITTI dataset into pre-defined path (in the code) as follows: '../data/kitti/training/velodyne_reduced/000007.bin' ?

**Comment by jhultman** [comment]
Hi, thanks for your question. Here are the links to download KITTI dataset:
- [calib](http://www.cvlibs.net/download.php?file=data_object_calib.zip)
- [label_2](http://www.cvlibs.net/download.php?file=data_object_label_2.zip)
- [velodyne](http://www.cvlibs.net/download.php?file=data_object_velodyne.zip)

`velodyne_reduced` refers to velodyne points after they have been filtered to remove points outside of camera field of view. I will release code later today to carry out this filtering.

Edit: Sorry, I just realized `000008.bin` is in the testing set, not the training set. You can replace with any other file in the training set, such as `000009.bin`.

**Comment by liyang0522** [comment]
in inference period，the points in the testing set are not filtered before and the velodyne_reduced/ only has the points in training set , so it means that  i should filter the points in testing set and then put them into the inference model ,am i right? thx
