### ISSUE TITLE
Recall of RPN stage

### ISSUE THREAD

**Issue by cqsnove** [jhultman/PV-RCNN#18]
Hi,I wrote the eval_rpn.py based on your code, and the results of operation are as follows:
total bbox recall(thresh=0.100): 12516 / 19060 = 0.656663
total bbox recall(thresh=0.300): 12242 / 19060 = 0.642288
total bbox recall(thresh=0.500): 11379 / 19060 = 0.597009
total bbox recall(thresh=0.700): 8201 / 19060 = 0.430273
total bbox recall(thresh=0.900): 653 / 19060 = 0.034260

The recall  with a threshold of 0.7 is quite different from that  in the paper. Is there something wrong with the code or some evaluation details I didn't pay attention to？

[eval_rpn.zip](https://github.com/jhultman/PV-RCNN/files/4403938/eval_rpn.zip)

**Comment by jhultman** [comment]
Hi, this library is still a work in progress. I have made several updates in a private branch which may bring results closer to those claimed in paper. (Among others, the smooth L1 loss is missing a scaling factor, the focal loss needs to be averaged by batch size, etc.) I will push those changes here soon in the next major release.
