### ISSUE TITLE
[Question] data format support

### ISSUE THREAD

**Issue by hedaniel7** [jhultman/PV-RCNN#26]
Hello there!

I want to use your repository for the Detection of doorways in building scans. The data format of my dataset is .fls, which I can convert to a lot of other data formats like for example .e57, .las, .pcd, .ply etc. But I see that you currently only support KITTI-bin format like most of SOTA 3D Detection repositories. 

1) Do you know by chance if it is in principle possible to convert my dataset into KITTI-bin format?
2) If not, do you think it is feasible to fork and extend your repository in such a way that it could also support other common point cloud formats? If yes, how hard would that be for a newbie?

Kind regards,

Daniel He

**Comment by jhultman** [comment]
Hi, I am glad you are interested in this project. I think supporting a different point cloud format should not require much work. You can try replacing the `read_velo` function call [here](https://github.com/jhultman/vision3d/blob/master/pvrcnn/dataset/kitti_dataset.py#L137). I would also recommend disabling the database sampling augmentation (may need to modify config.yaml or comment out some lines in the code).

I suspect the more difficult part will be ensuring the ground truth data is in a compatible format. You will need to write a `Dataset` class which produces the 7 degree of freedom bounding box (x, y, z, w, l, h, yaw) and the metadata (category, box_ignore flag).
